# Pass an array of joint velocities directly to the joints
joint_group_velocity_controller:
   type: velocity_controllers/JointGroupVelocityController
   joints:       
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7