joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  gains:
    joint1: {p: 1, i: 0.0, d: 0.0, i_clamp: 1}
    joint2: {p: 1, i: 0.0, d: 0.0, i_clamp: 1}
    joint3: {p: 1, i: 0.0, d: 0.0, i_clamp: 1}
    joint4: {p: 1, i: 0.0, d: 0.0, i_clamp: 1}
    joint5: {p: 1, i: 0.0, d: 0.0, i_clamp: 1}
  velocity_ff:
    joint1: 0.82
    joint2: 0.82
    joint3: 0.82
    joint4: 0.82
    joint5: 0.82
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
  stop_trajectory_duration: 0.2
  state_publish_rate:  25
  action_monitor_rate: 10